#Set session title
new_tab Mission Control
layout tall

# Window 1: 
launch bash -c "btop"

# Window 2:
launch bash -c "cava"

#Window 3:
launch --location=hsplit --bias=70 env RUN_MISSION_CONTROL=1 bash
# RUN_MISSION_CONTROL is defined at ~/.bashrc:
# if [ "$RUN_MISSION_CONTROL" = "1" ]; then
#   unset RUN_MISSION_CONTROL
#   fastfetch
#   echo -e ' ------------------------------- Welcome to Terminal ------------------------------- '
#   echo -e 'placeholder'
# fi
# 
#
